[package]
name = "cbp2clangd"
version = "1.0.0"
edition = "2024"

[dependencies]
roxmltree = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }
